Repository 33th-SOPKATHON-TEAM-APP3/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [feat] 엔티티 설계
  src/main/java/org/sopt/sopkathon/iosthree/domain/Answer.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/ExampleDomain.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/Question.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/SignupResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/User.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/ExampleJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/UserJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/ExampleService.java
  src/main/java/org/sopt/sopkathon/iosthree/service/UserService.java
Labels: FEAT, 수현 🐤

#4 [feat] Answer 도메인 관련
  src/main/java/org/sopt/sopkathon/iosthree/controller/AnswerController.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/AnswerJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/AnswerService.java
Labels: FEAT, 지영 🐦

#8 [feat] 버그 수정 + 오늘의 답변 저장 API
  src/main/java/org/sopt/sopkathon/iosthree/common/ApiResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/AnswerController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/request/TodayAnswerRequest.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/TodayAnswerResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/Answer.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/QuestionJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/UserJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/AnswerService.java
Labels: BUG, FEAT, 지영 🐦

#7 [feat] 회원가입 로그인 구현
  src/main/java/org/sopt/sopkathon/iosthree/common/ApiResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/UserController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/request/RequestDtoExample.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/request/SignUpRequest.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/SignUpResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/SignupResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/User.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Error.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/model/NotFoundException.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/UserJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/UserService.java
Labels: FEAT, 수현 🐤

#12 [feat] 나의 답변 조회 API 추가
  src/main/java/org/sopt/sopkathon/iosthree/common/ApiResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/AnswerController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/MyAnswerResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/QuestionDto.java
  src/main/java/org/sopt/sopkathon/iosthree/domain/Answer.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/AnswerJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/AnswerService.java
Labels: FEAT, 지영 🐦

#11 [feat] 오늘의 질문 조회
  src/main/java/org/sopt/sopkathon/iosthree/controller/QuestionController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/TodayQuestion.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/QuestionJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/QuestionService.java
Labels: FEAT, 수현 🐤

#15 [feat] 랜덤 답변 조회 API
  src/main/java/org/sopt/sopkathon/iosthree/controller/AnswerController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/RandomAnswerResponse.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/AnswerJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/AnswerService.java
Labels: FEAT, 지영 🐦

#17 [fix] 오늘의 질문 완료하면 isAnswered 값 바꾸기
  src/main/java/org/sopt/sopkathon/iosthree/domain/User.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/service/AnswerService.java
Labels: BUG, 지영 🐦

#18 [feat] 랜덤 리스트 로직
  src/main/java/org/sopt/sopkathon/iosthree/controller/QuestionController.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/QuestionDto.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/QuestionListDto.java
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/TodayQuestion.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/AnswerJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/QuestionService.java
Labels: FEAT

#19 [fix] 수정 localDate
  src/main/java/org/sopt/sopkathon/iosthree/domain/Question.java
  src/main/java/org/sopt/sopkathon/iosthree/infrastructure/QuestionJpaRepository.java
  src/main/java/org/sopt/sopkathon/iosthree/service/QuestionService.java
Labels: BUG

#21 [fix] questionName 변경
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/TodayQuestion.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
Labels: REFACTOR

#22 Main 통합
  src/main/java/org/sopt/sopkathon/iosthree/controller/dto/response/TodayQuestion.java
  src/main/java/org/sopt/sopkathon/iosthree/exception/Success.java
Labels: REFACTOR

#23 [bug] 유저생성로직 수정
  src/main/java/org/sopt/sopkathon/iosthree/service/UserService.java
Labels: BUG

#24 [refactor] 리드미 병합
  README.md
Labels: REFACTOR

#26 bug/25
  src/main/java/org/sopt/sopkathon/iosthree/service/UserService.java
Labels: BUG, 수현 🐤

#27 버그 수정 merge
  src/main/java/org/sopt/sopkathon/iosthree/service/UserService.java
Labels: BUG, UPDATE
